package io.graphine.test.model;

import io.graphine.core.annotation.Entity;
import io.graphine.core.annotation.Id;
import lombok.*;

import java.util.UUID;

/**
 * @author Oleg Marchenko
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@ToString
@Entity
public class Genre {
    @Id(autogenerated = false)
    private UUID id;
    private String name;
}
