package io.graphine.processor.metadata.model.entity.attribute;

import io.graphine.core.annotation.Id;

import javax.lang.model.element.VariableElement;

import static java.util.Objects.nonNull;

/**
 * @author Oleg Marchenko
 */
public class IdentifierMetadata extends AttributeMetadata {
    private final boolean autogenerated;

    public IdentifierMetadata(VariableElement element, String column, boolean autogenerated) {
        super(element, column);
        this.autogenerated = autogenerated;
    }

    public boolean isAutogenerated() {
        return autogenerated;
    }

    @Override
    public String toString() {
        return name + " [" + column + ", ID]";
    }

    public static boolean isIdentifier(VariableElement fieldElement) {
        return nonNull(fieldElement.getAnnotation(Id.class));
    }
}
