package io.graphine.processor.metadata.factory.entity;

import io.graphine.core.annotation.Attribute;
import io.graphine.core.annotation.Id;
import io.graphine.processor.metadata.model.entity.attribute.AttributeMetadata;
import io.graphine.processor.metadata.model.entity.attribute.EmbeddedAttribute;
import io.graphine.processor.metadata.model.entity.attribute.IdentifierMetadata;
import io.graphine.processor.support.naming.pipeline.ColumnNamingPipeline;

import javax.lang.model.element.VariableElement;

import static io.graphine.processor.metadata.model.entity.attribute.EmbeddedAttribute.isEmbedded;
import static io.graphine.processor.metadata.model.entity.attribute.IdentifierMetadata.isIdentifier;
import static io.graphine.processor.util.StringUtils.isEmpty;
import static java.util.Objects.nonNull;

/**
 * @author Oleg Marchenko
 */
public final class AttributeMetadataFactory {
    private final ColumnNamingPipeline columnNamingPipeline;

    public AttributeMetadataFactory(ColumnNamingPipeline columnNamingPipeline) {
        this.columnNamingPipeline = columnNamingPipeline;
    }

    public AttributeMetadata createAttribute(VariableElement fieldElement) {
        String column = getColumn(fieldElement);
        if (isIdentifier(fieldElement)) {
            Id id = fieldElement.getAnnotation(Id.class);
            return new IdentifierMetadata(fieldElement, column, id.autogenerated());
        }
        if (isEmbedded(fieldElement)) {
            return new EmbeddedAttribute(fieldElement);
        }
        return new AttributeMetadata(fieldElement, column);
    }

    private String getColumn(VariableElement element) {
        String column = null;

        Attribute attribute = element.getAnnotation(Attribute.class);
        if (nonNull(attribute)) {
            column = attribute.column();
        }
        if (isEmpty(column)) {
            String attributeName = element.getSimpleName().toString();
            column = columnNamingPipeline.transform(attributeName);
        }
        return column;
    }
}
