package io.graphine.processor.metadata;

import javax.lang.model.element.VariableElement;

/**
 * @author Oleg Marchenko
 */
public class IdentifierMetadata extends AttributeMetadata {
    private final boolean autogenerated;

    public IdentifierMetadata(VariableElement element, String column, boolean autogenerated) {
        super(element, column);
        this.autogenerated = autogenerated;
    }

    public boolean isAutogenerated() {
        return autogenerated;
    }

    @Override
    public String toString() {
        return name + " [" + column + ", ID]";
    }
}
